import pandas as pd, numpy as np, json
d=pd.read_csv("/home/user/Bot2/ikiz_k25_cap25_islemler.csv")
s=d.strategy_scores.apply(json.loads)
print(d.shape, d.kol.value_counts().to_dict(), d.exit_reason.value_counts().to_dict())
print(pd.Series([tuple(sorted(x.keys())) for x in s]).value_counts())
d['ie']=s.apply(lambda x:x['intended_entry']); d['sl0']=s.apply(lambda x:x['sl0']); d['strat']=s.apply(lambda x:x['strategy'])
d['mh']=s.apply(lambda x:x.get('max_hold'))
print((d.strat==d.kol).mean())
sg=np.where(d.side=='long',1,-1)
print("slip_in bp by kol:", (sg*(d.entry_price/d.ie-1)*1e4).groupby(d.kol).describe())
print("sl_price vs sl0 rel diff:", ((d.sl_price-d.sl0).abs()/d.sl0).describe())
print("R col vs pnl/(q*stop):", (d.R - d.pnl_usdt/(d.quantity*(d.ie-d.sl0).abs())).abs().max())
print(d.mh.value_counts(dropna=False).head())
print(d.groupby('kol').symbol.unique())
print(d.entry_time.head(3).tolist(), d.giris.head(2).tolist())
